services:
  dev-enclave:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: dev-enclave
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - .vscode_extensions:/root/.vscode-server
    user: root
